### ISSUE TITLE
Work fine, but need some enhancement 

### ISSUE THREAD

**Issue by Theliel** [Angelelz/WinHelloUnlock#1]
Thanks for the complement. In general terms it works quite well and I missed such a complement, but I think it would be possible to improve it quite a bit with 2-3 adjustments

First of all, it suffers from the most common problem when playing with Windows Hello, and that is that the authentication windows appears behind, in the background, instead of in the foreground, so sometimes there is even to "search" for Windows Hello screen.

On the other hand, it would be much more "clean" (as does KeePassWinHello), only show the screen of traditional authentication (composite passwords) in case of aborting Windows Hello authentication, actually, both Windows are present

**Comment by Angelelz** [comment]
I've seen the first issue a couple of times, but I don't know how to fix it because I have not find a way to reliably reproduce. Do you use Secure Desktop?

As for the second, I actually used mostly the same method calls, but I'll take a look.

**Comment by Theliel** [comment]
No, I dont use Secure Desktop. 

The first problem should not be a simple issue, as I say is "common" in applications that use Windows Hello. Many work correctly, but it is not the first time I see such behavior. There must be some workaround or some way to solve it ...

In any case, thank you for your time.

**Comment by Angelelz** [comment]
I am testing a new way of unlocking the database that is supposed to only show the Windows Security Prompt on [This](https://github.com/Angelelz/WinHelloUnlock/files/3470372/WinHelloUnlock.zip) development build. It would be helpful if you could test it out.
I think the Windows Security prompt not showing up in foreground is related to any user input made between the time the method is called and the actual window appearing, but I'm not completely sure. I'm still working on it, but it probably won't get fixed because of the limited control over the prompt.
The file attached is built from the NoKeyPromptFormTest branch, so you can take a look at the code

**Comment by Theliel** [comment]
Hi @Angelelz 

The new version fix the second problem, testing since some hours and seen to work fine (about this issue), now, traditional Auth Windows only is called after two aborts. Perfect.

Now, remaining issues I have detected. My KeePass DB is blocked once I minimize it, which sends it directly to the system tray.

-If KeePass is called from the system tray, the Authentication screen always appears below, 

-If it is called from the taskbar it appears in front

-If it is called externally, for example through KeePassHTTP-Connector visiting a web with authentication, it always appears behind, but also 2 or 3 authentication windows (Windows Hello), instead of just one. I haven't looked at the code of some extensions, maybe KeePass is called more than once to make sure, and that makes the window appear multiple times, I'll take a look

**Comment by Angelelz** [comment]
Thank you for providing this feedback, It has been very helpful. 

-Right now I have not been able to reproduce the first issue you mention, it only happens when you call Keepass more than once (by clicking the tray icon repeatedly or hitting Ctrl+Alt+k repeatedly too). But I don't think I can do much about it since it is user input.

-The second Issue you mention is the expected behaviour.

-The third it's known bug since it's happening with [KeepassWinHello](https://github.com/sirAndros/KeePassWinHello/issues/19) also. But I still added some logic to avoid it in the EnsureForeground Branch.

Also in this branch I implemented a way to try to put Windows Security prompt to the foreground. I kindly ask you to test again with [this](https://github.com/Angelelz/WinHelloUnlock/files/3473382/WinHelloUnlock.zip) build.

Thanks again for the help.

**Comment by Angelelz** [comment]
I've been using this build for 2 days now and I have not seen the issue again, I'll prepare the next release with this changes and close here.

**Comment by Theliel** [comment]
Thank again @Angelelz 

-The last version fix (or maybe was related to another thing) my multiple auth Windows, maybe was something in the code or something in browser or... anyway, only one windows appear now.

-About foreground/background, more or less equal. Launched from tray icon auth Windows is in background, the same if called from browser or Ctrl+Alt+k.  Auth Windows only are in foreground (for me) once open and DB blocked, called from taskbar. 

Thank for your work

**Comment by Angelelz** [comment]
I reopened the issue.
I forced Windows Security Prompt to foreground even if user tries to change focus. The changes are in SetForeground2 branch if you want to check them out. 
[WinHelloUnlock.zip](https://github.com/Angelelz/WinHelloUnlock/files/3488607/WinHelloUnlock.zip)
Please try this one and confirm fix to close again.

**Comment by Theliel** [comment]
Hi @Angelelz 

Working perfectly now, no matter where the application is called from, it always brings it to the foreground finally, right now I don't detect any other issue,  I'll be aware anyway

Thank a lot, really useful add-on

**Comment by Angelelz** [comment]
Great, happy it finally works because I could never reproduce.
Anyway, please open another issue with that question, because it is unrelated to this one.

**Comment by Angelelz** [comment]
Closed with [v0.99.2](https://github.com/Angelelz/WinHelloUnlock/releases/tag/v0.99.2)
