### ISSUE TITLE
[Suggestion] Improve unlock mechanism when changing master key

### ISSUE THREAD

**Issue by GoldenHashtag** [Angelelz/WinHelloUnlock#12]
Change master key after setting up Windows Hello, then lock and unlock the database, you'll see that this plugin fails unlocking the database.
![image](https://user-images.githubusercontent.com/40300931/63218811-595c7f00-c196-11e9-8ce1-f0d835d6e1eb.png)
1)It should prompt for standard unlock when failed unlocking with stored key;
2)It should check if composite key is still unlockable after unlocking database with standard unlock prompt;
3)It should ask for setting up Windows Hello again after changing the master key.

**Comment by Angelelz** [comment]
No. 1 should be a good addition.
No. 2 could be added but I don't think it's high priority.
No. 3 I have to check if there is any "ChangedMasterKey" event I can subscribe to, to be doable.

**Comment by Angelelz** [comment]
Ok, after tinkering a bit with the code:
No. 1 will be fixed but I will also add a warning after the deletion of WinHelloUnlock data. That way, when you unlock again (with standard prompt), the database will be treated like a new database and you will be asked to create WinHelloUnlock data.
No. 2 will not be added because the plugin would need to prompt the user for Windows Hello auth in order to check whether it can unlock the database.
No. 3 will not be added because there no event that notifies me whenever a database's master key has been changed.
