### ISSUE TITLE
WinHelloUnlock Prompt Popup position is not remembered

### ISSUE THREAD

**Issue by sambul13** [Angelelz/WinHelloUnlock#20]
**Describe the bug**
WinHelloUnlock Prompt Popup position is not remembered after moved by a user. Next time it still appears in original place in the middle of monitor screen.

**To Reproduce**
1. Open KeePass. WinHelloUnlock Popup appears. 
2. Move the popup window and login by fingerprint
3. Exit KeePass or Lock the DB.
4. Re-activate KeePass to relogin.
5. WinHelloUnlock Popup appears again in the middle of screen

**Expected behavior**
The Popup should remember its last position, when fingerprint scan resulted in entry to KeePass DB.

In addition, the plugin's file has DLL extension instead of PLGX.

**Comment by Angelelz** [comment]
Windows Hello API does not provide control over the position of the prompt. The prompt is handled by Windows and it doesn't report position (Or change to it) to the caller. It could be possible to manage it's position with some other methods but it would be too convoluted and I think outside the scope of the plugin.
I have tried to create the PLGX file but it fail to work due to incompatibility with the way I reference Windows UWP APIs (I think). I could check it but please open a different issue for it.

**Comment by sambul13** [comment]
To my observation, KeePassWinHello plugin opens the Prompt right on top of KeePass open window. If you move position of the open KeePass window, next time the Prompt will open in the new window position. Pls re-open this bug. :)

**Comment by Angelelz** [comment]
I did not understand what you meant. KeePass window position is handled by the program itself, and it remembers it. On the other hand, Windows Security Prompt position is handled by Windows and the API does not provide a method to change it.
To be able to remember it, I would need to write to some config file and somehow apply this setting every time the prompt is called. Way too complex solution for just a prompt position that you don't even need to touch that much!
