### ISSUE TITLE
Error first time setting up 

### ISSUE THREAD

**Issue by Gilbert535** [Angelelz/WinHelloUnlock#37]
After confirming I want to set  WindowsHelloUnlock, I enter my PIN and receive this message:

Error saving the composite Key: Value cannot be Null
Parameter name:a

I use Windows 10 version 1909
I uses a master password along with a key file on a secure desktop to open my database.

EDIT:  Solved the issue by going to Tools/Options/Security and add a tick mark beside "remember master password (in encrypted form)..."

Now the plugin works beautifully. Thanks! 

My database is stored on ICloud but I tested with a copy on my desktop and got same result.

**Comment by Angelelz** [comment]
Cool, I've never thought of this issue. So the plugin takes the composite key from memory, that's why you see the error. I'll try to find a better way to handle this. Thanks for reporting and finding the solution!

**Comment by Gilbert535** [comment]
Hello,

 

In fact, as far as I can see, the extension does not take the composite key but the  master password alone. To be honest, I prefer it that way from a safety perspective. I tested it by removing the key file from my system and received an error message. 

 

Many thanks for your time in programing this plugin.

 

Gilbert

**Comment by Angelelz** [comment]
Regarding the key file, the plugin only saves (encrypted) its path and filename, not the actual information to unlock the database. So unless you have the keyfile in the same folder with the same name, the plugin can't unlock the database.
Anyway, what I'm missing to close this issue is handle this error differently, as mentioned [here](https://sourceforge.net/p/keepass/discussion/329220/thread/62b0b650/#4e05).

**Comment by Angelelz** [comment]
Will be fixed in next release. Master branch already updated.
