### ISSUE TITLE
Before install

### ISSUE THREAD

**Issue by gh-SAngeli** [Angelelz/WinHelloUnlock#71]
Hi,
not being able to send a message to the developer I wish to ask two questions before I install this plugin.

**1.** is this KeePass Plugins fully working or do I have to expect some problems?
I ask this question as do not want to start having random issues. I run Windows 11 and KeePass ver. 2.54

**2.** after having installed this plugin will the master password remain the same? I ask this question because I use to have the same copy of KeeyPass database I use on my PC also on my smartphone. So, I must be able to use the same master password on both devices while on my PC I can also use biometrics.

Please let me know. Many thanks

**Comment by Angelelz** [comment]
Hello,
The plugin should run without issues. It's been a long time since I've used it but it relies on Windows APIs that are still relevant.
If you find something you don't like you can uninstall it without any repercussions.
The plugin will not change or affect your password in any way. It will just encrypt it and save it in a safe location.

**Comment by Angelelz** [comment]
Hello,
The plugin should run without issues. It's been a long time since I've used it but it relies on Windows APIs that are still relevant.
If you find something you don't like you can uninstall it without any repercussions.
The plugin will not change or affect your password in any way. It will just encrypt it and save it in a safe location.

**Comment by gh-SAngeli** [comment]
Hi,
many thanks for your reply. If I find something that I do not like I will report it here in this thread. I do not know if you keep this plugin updated or enhance it but I wish to contribute to your work if needed it.
Thank you

**Comment by Angelelz** [comment]
It's been a long time since I've committed any code to this repo. I believe it's feature complete. There are issues related to hardware that I obviously can't reproduce, therefore I can't fix. For sure let me know if you find any issues I could help you with.
