### ISSUE TITLE
Default Windows Hello Authtentificator?

### ISSUE THREAD

**Issue by Theliel** [Angelelz/WinHelloUnlock#8]
Hi again @Angelelz 

I don't know if its related to Windows Hello API... 

Windows Hello support multiple authenticators, like Pin, Fingerprint, Face recognition or security keys (through FIDO2). In some environments, we have more than one authtentificator. Sometimes fingerprint is preferred for me, but others i prefer Face Recognition, is faster and more accuracy. Of course, you always can choose what authentificator to use, but by default one is chosen, and a couple of clicks are necessary to select a different one. 

I do not know if it is configuration policy, if when multiple systems are present, you can choose a system always prevails over the other, or if it is possible to configure that the last one used is the one that is by default. Or perhaps, as I say, the API does not have any power over it and it is Windows who establishes one or the other as the principal.

In my case, the ideal would be to be able to use facial identification for KeePass by default, it would be even faster. I can remove my fingerprint or disable it on Windows Hello, but I don't want to remove it from the system. Similarly, for example, when I log in to Windows, it remembers the last system used, and it is the one that shows me the next time, which would really be ideal.

**Comment by Angelelz** [comment]
After a little research, I can say this issue is a bit out of the scope of this plugin. You can actually set default Credential Provider for Authentication by following [this](https://www.top-password.com/knowledge/set-default-sign-in-option-in-windows-10.html) guide. You can also enforce this setting (not allow it to change) by:
- [Batch file](https://superuser.com/a/1333786) on a scheduled task.
- [Local Group Policy](https://superuser.com/a/1366012)
- [Changing the permissions](https://superuser.com/a/1265040) for the particular Registry key so that system can't change it again.

That being said, I will leave the issue open, if enough users are interested, I could look more in depth and evaluate if I can implement a button or a setting for the plugin to change the authentication method automatically.

**Comment by Theliel** [comment]
Thank for your Interest,

Sadly those tricks only work for Windows Logon, my default provider for logon are already face recognition: {8AF662BF-65A0-4D0A-A540-A338A999D36F}

The truth is that I have been looking for some way to do it for some time, but I have more and more doubts about it

**Comment by Krammig** [comment]
I would very much like to try this however I am getting a lot of compile errors, no doubt my fault here. 
I am running VS 2015. 
Unzipped your code and tried to Build. 
Is there anything special I need to take into account ?
Example - type or namespace name OptionsForm could not be found.
Thanks

**Comment by Angelelz** [comment]
@Krammig This question is not related to the issue in this thread, please open a new issue to ask your question. That way, if there is another person with the same problem or question, it's easier to find. Thanks for your interest.
